export enum QueryKey {
  gender = "ge",
  paySystem = "pay",
  originParts = "ori",
  aboutCategory = "abo",
  parts = "par",
  skinCollor = "sk",
  hair = "ha",
  roomType = "ro",
  interior = "in",
  staff = "sta",
  card = "ca",
  loan = "lo",
  contract = "co",
  option = "op",
}
